version: '2'
services:
  db:
    image: mongo
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp # . means your current directory
                 # /myapp means the directory /myapp in the container
                 # : means to map the first one with the second and build a volume
    ports:
      - "3000:3000" # port will map the 3000 from container to system
    expose:
      - "3000" # will expose the port of the container in the network of containers.
    depends_on:
      - db
  frontend:
    image: roy_forums_ui
    command: npm run wds-docker
    ports:
      - "8080:9000"
    expose:
      - "9000"
    depends_on:
      - web
# docker-compose run web rails new . --force --database=mongo --skip-bundle